Parameters:
  # Definindo parâmetros de entrada
  BucketNamePrefix:
    # Parâmetro que recebe o prefixo do Bucket S3
    Type: String
    Description: Prefixo a ser adicionado ao nome do Bucket S3.

Resources:
  # Definindo os recursos utilizados
  MeuBucketTeste:
    # ID lógico do recurso   
    Type: AWS::S3::Bucket # Tipo do recurso (Bucket S3)
    Properties:
      # Propriedades do recurso
      BucketName: !Sub ${BucketNamePrefix}-bucket-${AWS::AccountId} # Nomeia o Bucket usando o prefixo passado nos parâmetros      
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          # Força a criptografia de todos os objetos armazenados
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        # Bloqueia o acesso público
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PolicyDoMeuBucketTeste:
    # ID lógico do recurso
    Type: AWS::S3::BucketPolicy # Tipo do recurso (policy de Bucket S3)
    Properties:
      # Propriedades do recurso
      Bucket: !Ref MeuBucketTeste # Aponta para o Bucket criado
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          # Bloqueia qualquer ação de usuário se a conexão não estiver criptografada
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt MeuBucketTeste.Arn
              - !Sub ${MeuBucketTeste.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'

Outputs:
  # Definindo valores de saída
  NomeBucket:
    Description: O nome completo do bucket S3 criado na stack.
    Value: !Ref MeuBucketTeste # Retorna o nome do bucket que criamos
